[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nexblue-api"
version = "0.1.0"
description = "Async client for the NexBlue OpenAPI"
readme = { text = "Async client for the NexBlue API.", content-type = "text/markdown" }
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [{ name = "NexBlue" }]
dependencies = ["aiohttp>=3.10"]

[project.optional-dependencies]
test = []

[tool.hatch.build.targets.wheel]
packages = ["nexblue_api"]
